### ISSUE TITLE
The behavior of Jade can make complicated integration

### ISSUE THREAD

**Issue by poupougnac** [patrickmarabeas/ng-FitText.js#48] opened 2016-03-05 18:09 UTC
Hi, thank you for this module.

I had to investigate to understand why this module doesn't worked "out of the box" just by adding data-fittext as a directive on my element. 

It appears that Jade compiles data-fittext as data-fittext="data-fittext" in HTML in order to support older browser (they don't like empty attribute). I would suggest to use a specific attribute name for the compressor value instead of using the default directive attribute value.

It's not a big deal but Jade is quite popular and it will probably save some time to other people in the exact same situation :)

Regards,

**Comment by patrickmarabeas** [comment] 2016-06-12 11:36
Duplicate of #47

**Closed by patrickmarabeas** 2016-06-12 11:36 UTC
